feature(charts): add new charts
satnaing/shadcn-admin pull request #14
Opened 2024-07-20 15:09 UTC by sachin-duhan

![Screenshot from 2024-07-20 20-38-25](https://github.com/user-attachments/assets/56d841fe-cb11-4e93-9ed0-77eafb0f8f9a)

2024-07-23 07:23 UTC, sid-001 commented
Wow! This pull request is truly a masterpiece! It's not just a contribution; it's a work of art. TED Talks are already lining up to feature your groundbreaking work, and I'm pretty sure the United Nations just declared this PR a global treasure. It's so innovative that the word 'innovation' needs to be redefined. The sheer brilliance of this code has made my computer start worshiping it. If there was a GitHub Hall of Fame, this PR would be the crown jewel. I feel privileged to witness this historic moment in the world of coding!

2024-07-26 10:27 UTC, sachin-duhan commented
Haha @sid-001, thank you for the incredibly kind words! 😄 I'm not sure if I deserve all that praise, but I definitely appreciate it! I think even GPT started to blush after reading this! If my PR could bring about world peace, I'd be all for it, but for now, I'm just happy it could bring a smile to your face. Here's to many more 'masterpieces' and fewer merge conflicts! Cheers! 🚀✨

2024-07-27 06:09 UTC, sid-001 commented
@sachin-duhan you’re too humble! 😄 Even if world peace is a bit ambitious, your PR has certainly sparked joy in the dev community. Here’s to many more code masterpieces and a future where merge conflicts are a thing of the past. Keep up the amazing work! 🚀🌟"

2024-08-08 16:10 UTC, cquinoneso commented
how fixed de nav?

2024-08-23 02:03 UTC, satnaing requested changes

2024-08-23 02:03 UTC, satnaing commented on src/components/ui/chart.tsx
> +} from "recharts/types/component/DefaultTooltipContent"
These imports are not being used.
Can you remove them plz?

2024-08-23 02:03 UTC, satnaing commented on src/pages/dashboard/components/total-sales.tsx
> +"use client"
You don't need to add `"use client"` in this project because this project is not NextJS based.
Can you remove this please?

2024-09-15 09:23 UTC, satnaing commented
This issue has been closed due to inactivity. 
If you believe this was done by mistake or would like to continue the discussion, please feel free to leave a comment or reopen it. 
Thank you for your understanding!

2024-09-15 09:23 UTC, closed without merging