fix #25 tried adding CI workflow
satnaing/shadcn-admin pull request #34
Opened 2024-09-27 10:24 UTC by ank-it07

**Description:**
This PR addresses #25 by introducing a CI flow for the repository using GitHub Actions. 
The workflow is failing due to missing Netlify credentials (NETLIFY_AUTH_TOKEN). Since I do not have access to the necessary credentials, deployment cannot proceed at this time.

I'm open to any suggestions or necessary changes to improve the PR. As I'm new to open-source contributions, I'd appreciate guidance on incorporating changes effectively.

![image](https://github.com/user-attachments/assets/f0b844fe-d6c8-4167-be51-86643653f1a1)

2024-10-13 11:54 UTC, satnaing requested changes

2024-10-13 11:54 UTC, satnaing commented on .github/workflows/Integration.yml
Can you rename the file to `ci.yml` plz?
Because I don't want to add Continuous Deployment to this repo since this can be different for each user.
Besides, I already have a CD pipeline in Netlify so I won't need that in this repo.

2024-10-13 11:54 UTC, satnaing commented on .github/workflows/Integration.yml
> +name: Integration
Rename this to `CI` or `Continuous Integration` please.

2024-10-13 11:54 UTC, satnaing commented on .github/workflows/Integration.yml
> +      - deployment
You can remove deployment since this is already implemented in the Netlify.

2024-10-13 11:54 UTC, satnaing commented on .github/workflows/Integration.yml
> +        uses: actions/checkout@v3
You can now use the latest one v4.
So, plz update this to `actions/checkout@v4`

2024-10-13 11:54 UTC, satnaing commented on .github/workflows/Integration.yml
> +        uses: actions/setup-node@v3
V4 plz. `actions/setup-node@v4`

2024-10-13 11:54 UTC, satnaing commented on .github/workflows/Integration.yml
> +          netlify deploy --prod --dir=dist --site=$NETLIFY_SITE_ID
As I said above, you can remove these.

2024-10-14 17:14 UTC, ank-it07 commented
Hi @satnaing 

I’ve made the changes to the CI workflow as you suggested. The deployment steps have been removed since you have a CD pipeline in place.
Please let me know if you need any further modifications or if everything looks good to proceed.

Thank you for your guidance!

2024-10-17 01:56 UTC, satnaing approved these changes

2024-10-17 01:57 UTC, merged

2024-10-17 01:58 UTC, satnaing commented
Thanks for your contribution. ✌🏼

2024-10-17 01:59 UTC, satnaing commented
Gosh
I forget to check one thing.
You need to merge into `main` branch tho.

2024-10-17 14:15 UTC, ank-it07 commented
Ahh! I see 
I'll go ahead and merge these changes into the main branch.
Thanks for pointing that out!